---
assets:
    execution_environments:
    -   credential:
            credential_type:
                kind: registry
                name: Container Registry
                type: credential_type
            name: Gitlab Registy Credential
            organization:
                name: Default
                type: organization
            type: credential
        description: ''
        image: registry.gitlab.com/redhatautomation/ansible_ee/ruch-network-ee:latest
        name: ruch-network-ee
        natural_key:
            name: ruch-network-ee
            type: execution_environment
        organization:
            name: Default
            type: organization
        pull: missing
changed: false
failed: false
...
