---
- name: Configure Certificate on IOS XE device
  hosts: cisco
  gather_facts: false

  vars:
    domain_name: ansible.local
    cert_file: ./rtr2.p12
    ca_cert: "{{ lookup('file', './certificates/cacert.cer').splitlines() }}"
    trustpoint: aaptest1
    certificate_on_host: false
    certificates: []
    certificates_outofdate: []

  tasks:
    - name: Get certificates from host
      ansible.netcommon.cli_command:
        command: "sho crypto pki certificates {{ trustpoint }}"
      register: certificates

    - name: Fail when hostname not in certificates
      ansible.builtin.fail:
        msg: The system may not be provisioned with a certificate
      when: inventory_hostname not in certificates.stdout

    - name: Debug Fact
      ansible.builtin.debug:
        msg: "{{ certificates }}"

    - name: "Parse CLI Output from show crypto pki certificates"
      vars:
        template: "/usr/local/lib/python3.9/site-packages/ntc_templates/templates/cisco_ios_show_crypto_pki_certificates.textfsm"
      ansible.builtin.set_fact:
        certs_parsed: "{{ certificates.stdout | parse_cli_textfsm(template) }}"

    - name: Get System Time
      ansible.builtin.command:
        cmd: 'date -u +"%H:%M:%S UTC %b %d %Y"'
      changed_when: false
      register: current_date
      delegate_to: ansible-1

    - name: Date Another Fact
      ansible.builtin.set_stats:
        data:
          certificates_outofdate: "true"
      when:
        - item.CERTIFICATE_TYPE == "Certificate"
        - "{{ (((item.END_DATE | to_datetime('%X UTC %b %d %Y')) - (current_date.stdout | to_datetime('%X UTC %b %d %Y'))).days) < 20}}"
      loop: "{{ certs_parsed }}"

...
