---
- name: Generate a client certificate using Demo CA
  hosts: ansible-1
  become: true
  gather_facts: false

  vars:
    client: "{{ data.client | default('rtr1')}}"
    days: '20'

  tasks:
    - name: Delete files
      ansible.builtin.file:
        path: "/tmp/{{ client }}.cer"
        state: absent

    - name: Generate Demo Certificate with OpenSSL from CSR
      ansible.builtin.expect:
        command: "openssl ca -config /opt/X509CA/openssl.cfg -in /tmp/{{ client }}_{{ trustpoint }}.csr -days {{ days }} -out /tmp/{{ client }}_{{ trustpoint }}.cer -notext"
        responses:
          'Enter pass phrase': "{{ ca_passphrase }}"
          'certificate?': 'y'
          'commit?': 'y'

    - name: Fix file permissions
      ansible.builtin.file:
        path: /tmp/{{ client }}.cer
        owner: student
        group: student
        mode: '0644'

...
