---
- name: Generate a client certificate using Demo CA
  hosts: ca-host
  become: false
  gather_facts: false

  vars:
    client: "{{ data.client | default('rtr1')}}"
    ca_passphrase: 'PASSW0RD'
    trustpoint: CACERT
    renewal_days: '21'

  tasks:
    - name: Delete files
      ansible.builtin.file:
        path: "/tmp/{{ client }}_{{ trustpoint }}.cer"
        state: absent
      become: true

    - name: Generate Demo Certificate with OpenSSL from CSR
      ansible.builtin.expect:
        command: "openssl ca -config /opt/X509CA/openssl.cfg -in /tmp/{{ client }}.csr -out /tmp/{{ client }}.cer -days {{ renewal_days }} -notext"
        responses:
          'Enter pass phrase': "{{ ca_passphrase }}"
          'certificate?': 'y'
          'commit?': 'y'


    # - name: Generate Demo Certificate with OpenSSL from CSR
    #   ansible.builtin.expect:
    #     command: >
    #       "openssl ca -config /opt/X509CA/openssl.cfg "
    #       "-in /tmp/{{ client }}_{{ trustpoint }}.csr "
    #       "-out /tmp/{{ client }}_{{ trustpoint }}.cer "
    #       "-days {{ renewal_days }} -notext"
    #     responses:
    #       'Enter pass phrase': "{{ ca_passphrase }}"
    #       'certificate?': 'y'
    #       'commit?': 'y'

    # - name: Fix file permissions
    #   ansible.builtin.file:
    #     path: /tmp/{{ client }}_{{ trustpoint }}.cer
    #     owner: juniper
    #     group: juniper
    #     mode: '0644'

...
