---
- name: Gather configuration information from NXOS devices
  hosts: cisco_routers
  gather_facts: no

  tasks:
  - name: Backup Config
    cisco.ios.ios_config:
      backup: true

  - name: Gather network information as structured data
    cisco.ios.ios_facts:
      gather_network_resources:
        - 'ntp_global'
        - 'logging_global'
        - 'hostname'
        - 'snmp_server'
        - 'vlans'
        - 'interfaces'
        - 'l2_interfaces'
        - 'l3_interfaces'
        - 'lag_interfaces'
        - 'lldp_interfaces'
        - 'lldp_global'
        - 'lacp'
        - 'lacp_interfaces'
        - 'service'
        - 'bgp_global'
        - 'bgp_address_family'
        - 'ospf_interfaces'
        - 'ospfv2'
        - 'ospfv3'
        - 'prefix_lists'
        - 'static_routes'
        - 'acl_interfaces'
      #gather_subset:
        #- '!min'
        #- all
    #register: ansible_network_resources

  - name: Print out
    ansible.builtin.debug:
      var: ansible_network_resources

#  - name: Store VLAN facts to host_vars
#    ansible.builtin.copy:
#      content: "{{ ansible_network_resources | to_nice_yaml }}"
#      dest: "./host_vars/{{ inventory_hostname }}"
#    delegate_to: localhost 
