---
- name: Configure IOS XE device
  hosts: cisco
  gather_facts: false
  vars:
    _domain_name_: ansible.local
  tasks:
    - name: Backup Config
      tags:
        - always
      cisco.ios.ios_config:
        backup: true

    - name: Configure hostname and domain name
      tags:
        - always
      cisco.ios.ios_system:
        hostname: "{{ hostname }}"
        domain_name: "{{ _domain_name_ }}"
        name_servers:
          - 8.8.8.8
        domain_search:
          - "{{ _domain_name_ }}"

    - name: Configure NTP
      tags:
        - never
        - ntp
      block:
        - name: Print out ntp configuration
          ansible.builtin.debug:
            msg: "{{ ntp_global }}"
            verbosity: 2

        - name: Combine host and group defined NTP configuration
          ansible.builtin.set_fact:
            device_ntp: "{{ ntp_global | combine(group_ntp_global | default({})) }}"

        - name: Update NTP Configuration
          cisco.ios.ios_ntp_global:
            config: "{{ device_ntp }}"
            state: replaced
          register: result

        - name: Print any NTP configuration changes
          ansible.builtin.debug:
            msg: "{{ result.commands }}"
      # End of NTP block tasks

    - name: Configure VLANs
      tags:
        - never
        - vlans
      block:
        - name: Print out host defined VLANs
          ansible.builtin.debug:
            var: vlans
            verbosity: 2

        - name: Print out group defined VLANs
          ansible.builtin.debug:
            var: group_network.vlans
            verbosity: 2

        - name: Combine host and group defined VLANs
          ansible.builtin.set_fact:
            device_vlans: "{{ vlans + (group_network_config.vlans | default([])) }}"

        - name: Make VLAN config changes by updating stored facts on the controller
          cisco.ios.ios_vlans:
            config: "{{ device_vlans }}"
            state: replaced
          register: result

        - name: Print any VLAN configuration changes
          ansible.builtin.debug:
            msg: "{{ result.commands }}"
      # End of VLAN block tasks

    - name: Configure interfaces
      tags:
        - never
        - interfaces
      block:
        - name: Print out interfaces
          ansible.builtin.debug:
            msg: "{{ interfaces }}"
            verbosity: 2

        - name: Make interface config changes based on host_vars data
          cisco.ios.ios_interfaces:
            config: "{{ interfaces }}"
            state: merged
          register: result

        - name: Print any interface configuration changes
          ansible.builtin.debug:
            msg: "{{ result.commands }}"
      # End of interfaces block tasks

    - name: Configure l2 interfaces
      tags:
        - never
        - interfaces
      block:
        - name: Print out interfaces
          ansible.builtin.debug:
            msg: "{{ l2_interfaces }}"
            verbosity: 2

        - name: Make interface config changes based on host_vars data
          cisco.ios.ios_l2_interfaces:
            config: "{{ l2_interfaces }}"
            state: merged
          register: result

        - name: Print any interface configuration changes
          ansible.builtin.debug:
            msg: "{{ result.commands }}"
      # End of interfaces block tasks

    - name: Configure L3 interface
      tags:
        - never
        - l3_interfaces
      block:
        - name: Print out L3 interfaces
          ansible.builtin.debug:
            msg: "{{ l3_interfaces }}"
            verbosity: 2

        - name: Make L3 interface config changes based on host_vars data
          cisco.ios.ios_l3_interfaces:
            config: "{{ l3_interfaces }}"
            state: merged
          register: result
          # check_mode: true

        - name: Print any L3 interface configuration changes
          ansible.builtin.debug:
            msg: "{{ result.commands }}"
      # end of l3_interfaces block tasks

    - name: Configure SNMPv3
      tags:
        - never
        - snmp
      block:
        - name: Print out snmp
          ansible.builtin.debug:
            msg: "{{ snmp_server }}"
            verbosity: 2

        - name: Make snmp config changes based on host_vars data
          cisco.ios.ios_snmp_server:
            config: "{{ snmp_server }}"
            state: merged
          register: result
          # check_mode: true

        - name: Print any snmp configuration changes
          ansible.builtin.debug:
            msg: "{{ result.commands }}"
      # end of l3_interfaces block tasks

...
