---
- name: Configure GRE Tunnels
  hosts: all
  gather_facts: no

  vars:
    cisco_rtr_1_public_ip: "18.189.209.195"
    #cisco_rtr_1_public_ip: "{{ hostvars['cisco-rtr-1']['ansible_host'] }}"
    cisco_rtr_2_public_ip: "3.137.129.183"
    #cisco_rtr_2_public_ip: "{{ hostvars['cisco-rtr-2']['ansible_host'] }}"
    cisco_rtr_3_public_ip: "3.142.154.41"
    #cisco_rtr_3_public_ip: "{{ hostvars['cisco-rtr-3']['ansible_host'] }}"
    cisco_rtr_4_public_ip: "18.189.98.51"
    #cisco_rtr_4_public_ip: "{{ hostvars['cisco-rtr-4']['ansible_host'] }}"

  tasks:


  - name: create tunnel interface R1 to R2
    ios_config:
      lines:
       - 'ip address 10.0.0.1 255.255.255.252'
       - 'tunnel source GigabitEthernet1'
       - 'tunnel destination {{ cisco_rtr_2_public_ip }}'
      parents: interface Tunnel 0
    when: '"cisco-rtr-1" in inventory_hostname'

  - name: create tunnel interface R1 to R2
    ios_config:
      lines:
       - 'ip address 10.0.0.2 255.255.255.252'
       - 'tunnel source GigabitEthernet1'
       - 'tunnel destination {{ cisco_rtr_1_public_ip }}'
      parents: interface Tunnel 0
    when: '"cisco-rtr-2" in inventory_hostname'

  - name: create tunnel interface R2 to R3
    ios_config:
      lines:
       - 'ip address 10.0.0.5 255.255.255.252'
       - 'tunnel source GigabitEthernet1'
       - 'tunnel destination {{ cisco_rtr_3_public_ip }}'
      parents: interface Tunnel 1
    when: '"cisco-rtr-2" in inventory_hostname'

  - name: create tunnel interface R2 to R3
    ios_config:
      lines:
       - 'ip address 10.0.0.6 255.255.255.252'
       - 'tunnel source GigabitEthernet1'
       - 'tunnel destination {{ cisco_rtr_2_public_ip }}'
      parents: interface Tunnel 1
    when: '"cisco-rtr-3" in inventory_hostname'

  - name: create tunnel interface R3 to R4
    ios_config:
      lines:
       - 'ip address 10.0.0.9 255.255.255.252'
       - 'tunnel source GigabitEthernet1'
       - 'tunnel destination {{ cisco_rtr_4_public_ip }}'
      parents: interface Tunnel 0
    when: '"cisco-rtr-3" in inventory_hostname'

  - name: create tunnel interface R2 to R3
    ios_config:
      lines:
       - 'ip address 10.0.0.10 255.255.255.252'
       - 'tunnel source GigabitEthernet1'
       - 'tunnel destination {{ cisco_rtr_3_public_ip }}'
      parents: interface Tunnel 0
    when: '"cisco-rtr-4" in inventory_hostname'
