---
- name: Gather configuration information from NXOS devices
  hosts: nexus
  gather_facts: no

  tasks:
  - name: Backup Config
    cisco.nxos.nxos_config:
      backup: true
    tags:
      - never
      - backup

  - name: Gather network information as structured data
    cisco.nxos.nxos_facts:
      gather_network_resources:
        - 'static_routes'
        - 'ntp_global'
        - 'logging_global'
        - 'hostname'
        - 'snmp_server'
        - 'vlans'
        - 'interfaces'
        - 'l2_interfaces'
        - 'l3_interfaces'
      gather_subset:
        - '!min'
        - '!all'

  - name: Print out
    ansible.builtin.debug:
      msg: "{{ ansible_network_resources }}"
      #var: ansible_facts.ansible_network_resources
      verbosity: 2

  - name: GitOps functions
    block:
    - name: Retrieve a repository from a distant location and make it available locally
      ansible.scm.git_retrieve:
        origin:
          url: "{{ git_url }}"
      register: repository
 
    - name: Debug repository data
      ansible.builtin.debug:
        var: repository
        verbosity: 2
 
    - name: Create a config_backups directory if it does not exist
      ansible.builtin.file:
        path: "{{ repository['path'] }}/config_backups"
        state: directory
        mode: '0755'
      when: ansible_facts.net_config is defined
 
    - name: Add to the repository
      ansible.builtin.copy:
        content: "{{ ansible_facts.net_config }}"
        dest: "{{ repository['path'] }}/config_backups/{{ inventory_hostname }}"
      when: ansible_facts.net_config is defined
      register: result

    - name: Create a host_vars directory if it does not exist
      ansible.builtin.file:
        path: "{{ repository['path'] }}/host_vars"
        state: directory
        mode: '0755'
      when: '"routing" in ansible_net_gather_subset'
 
    - name: Add global facts to the repository
      ansible.builtin.lineinfile:
        line: "{{ ansible_facts | to_nice_yaml }}"
        path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}"
        create: yes
      when: '"routing" in ansible_net_gather_subset'
      register: result
 
    - name: Add security rules to the host_vars repository
      ansible.builtin.lineinfile:
        line: "{{ registered_sec_rules | to_nice_yaml }}"
        path: "{{ repository['path'] }}/host_vars/{{ inventory_hostname }}"
        create: yes
      when: registered_sec_rules is defined
 
    - name: Set date_time variable
      ansible.builtin.set_fact:
        date_time: "{{ lookup ('pipe', 'date +%Y-%m-%d%H:%M:%S') }}"
 
    - name: Publish the changes
      ansible.scm.git_publish:
        commit:
          message: "Backup at {{ date_time }}"
        include: "--all"
        path: "{{ repository['path'] }}"
        user:
          name: "Todd Ruch"
          email: truch@redhat.com
      when: result.changed
    ### End of GitOps Block
    tags:
      - gitops
      - never

#  - name: Store VLAN facts to host_vars
#    delegate_to: laptop
#    ansible.builtin.copy:
#      content: "{{ ansible_network_resources | to_nice_yaml }}"
#      dest: "/home/admin/{{ inventory_hostname }}"
#    register: result

  - name: Ensure config did not change
    ansible.builtin.assert: 
      that: not result.changed


