---
- name: Use case | Only admin user on network device
  hosts: nxosv1
  gather_facts: no

  tasks:
    - name: print thing
      ansible.builtin.debug:
        msg: beginning

    - name: get facts
      cisco.nxos.nxos_facts:
        gather_subset:
          - config

    - name: print facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts.net_config | to_nice_json }}"
          
    - name: remove all users except admin
      cisco.nxos.nxos_user:
        purge: true

    - name: create a new user
      cisco.nxos.nxos_user:
        name: ansible
        sshkey: "{{ ansible_pub_key }}"
        state: present
        role: network-admin

  handlers: 
    - name: changed
      ansible.builtin.debug:
        msg: "something changed"

